---
title: "Week 10"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
```
## Load Lidar Data
```{r}
# Digital surface model
dsm <- rast(here('data', 'SJER2013_DSM.tif'))

# Digital terrain model, ground returns
dtm <- rast(here('data', 'SJER2013_DTM.tif'))

test_raster <- c(dsm, dtm)

# create canopy height model
chm <- dsm - dtm
```
## Load vegetation plot geometries
```{r}
plot_centroids <- st_read(here('data', 'PlotCentroids', 'SJERPlotCentroids_Buffer.shp')) %>%
  st_transform(., crs = st_crs(chm))
```

```{r}
tm_shape(chm) +
  tm_raster(title = 'Canopy Height Model') +
  tm_shape(plot_centroids) +
  tm_polygons()
```
## Load vegetation survey data
```{r}
veg_surveys <- read_csv(here('data', 'VegetationData', 'D17_2013_vegStr.csv')) |> 
  group_by(plotid) |> 
  summarise('survey_height' = max(stemheight, na.rm = TRUE))
```
```{r}
extract_chm_height <- terra::extract(chm, plot_centroids, fun = max) |> 
  rename(chm_height = SJER2013_DSM) |> 
  select(chm_height)


plot_centroids <- cbind(plot_centroids, extract_chm_height) %>%
  left_join(., veg_surveys, by = c('Plot_ID' = 'plotid'))
  
```

```{r}
ggplot(plot_centroids, aes(x = chm_height, y = survey_height)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  geom_abline(slope = 1, intercept = 0, alpha = 0.5, lty = 2) +
  xlab('Maximum Measured Height (Lidar)') +
  ylab('Maximum Measure height (survey)') +
  ggtitle('Validating Lidar measurements') +
  theme_minimal()
```






